kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: insecure
  labels:
    app: insecure
spec:
  replicas: 5
  selector:
    matchLabels:
      app: insecure
  serviceName: "insecure"
  template:
    metadata:
      labels:
        app: insecure
    spec:
      containers:
      - name: insecure
        image: 'insecure:latest'
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /home/admin
            name: home-admin
            readOnly: true
          - mountPath: /etc/shadow
            name: shadow
            readOnly: true
          - mountPath: /etc/passwd
            name: passwd
            readOnly: true
          - mountPath: /var/log
            name: security-event
      volumes:
        - name: home-admin
          hostPath:
            path: /home/admin
            type: Directory
        - name: security-event
          hostPath:
            path: /var/log
            type: Directory
        - name: shadow
          hostPath:
            path: /etc/shadow
        - name: passwd
          hostPath:
            path: /etc/passwd
